kind: PersistentVolume 
apiVersion: v1 
metadata: 
  name: {{ .Values.postgres.name }}-pv-volume 
  labels: 
    type: local 
    app: {{ .Values.postgres.name }} 
spec: 
  storageClassName: microk8s-hostpath 
  capacity: 
    storage: 5Gi 
  accessModes: 
    - ReadWriteMany 
  hostPath: 
    path: "/opt/postgres/data" 
--- 
kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: {{ .Values.postgres.name }}-pv-claim 
  labels:
    app: {{ .Values.postgres.name }} 
spec: 
  storageClassName: microk8s-hostpath 
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 5Gi