apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: {{ .Values.postgres.name }}-config 
  labels: 
    app: {{ .Values.postgres.name }} 
data: 
  POSTGRES_USER: admin
  POSTGRES_HOST: localhost
  POSTGRES_DB: postgres