apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.yugiapi.name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.yugiapi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.yugiapi.name }}
    spec:
      containers:
        - name: yugiapi
          image: {{ .Values.yugiapi.image.repository }}:{{ .Values.yugiapi.image.tag }}
          ports:
            - containerPort: {{ .Values.yugiapi.service.port }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.name }}-secret
                  key: POSTGRES_PASSWORD
