# templates/yugiwebapp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-yugiwebapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yugiwebapp
  template:
    metadata:
      labels:
        app: yugiwebapp
    spec:
      containers:
        - name: yugiwebapp
          image: {{ .Values.yugiwebapp.image.repository }}:{{ .Values.yugiwebapp.image.tag }}
          ports:
            - containerPort: {{ .Values.yugiwebapp.service.port }}