# templates/yugiapi-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-yugiapi-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.yugiapi.service.port }}
      targetPort: {{ .Values.yugiapi.service.port }}
  selector:
    app: yugiapi