# templates/yugiapi-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-yugiapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yugiapi
  template:
    metadata:
      labels:
        app: yugiapi
    spec:
      containers:
        - name: yugiapi
          image: {{ .Values.yugiapi.image.repository }}:{{ .Values.yugiapi.image.tag }}
          ports:
            - containerPort: 5000