# templates/yugiwebapp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.yugiwebapp.name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.yugiwebapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.yugiwebapp.name }}
    spec:
      containers:
        - name: {{ .Values.yugiwebapp.name }}
          image: {{ .Values.yugiwebapp.image.repository }}:{{ .Values.yugiwebapp.image.tag }}
          ports:
            - containerPort: {{ .Values.yugiwebapp.service.port }}