# templates/yugiwebapp-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.yugiwebapp.name }}-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.yugiwebapp.service.port }}
      targetPort: {{ .Values.yugiwebapp.service.port }}
  selector:
    app: {{ .Values.yugiwebapp.name }}